# Generated by Django 4.2 on 2025-05-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('demoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailordetail',
            name='user_permissionss',
        ),
        migrations.AlterField(
            model_name='tailordetail',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='tailordetail_set', to='auth.permission'),
        ),
    ]
