# Generated by Django 4.2 on 2025-05-19 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0002_remove_tailordetail_user_permissionss_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tailordetail',
            name='passport_size',
        ),
    ]
